columnSuffix: null
contentColumnType: string
fieldGroup: 400b3ccf-4aa3-4b6a-a94a-46eb13007298 # Common
handle: raum
instructions: null
name: Raum
searchable: false
settings:
  contentTable: '{{%matrixcontent_raum}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
