dateModified: 1713654072
email:
  fromEmail: matthias.ruetten@gmail.com
  fromName: 'Ferienwohnung Dornumersiel'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    80d9c334-541d-4f23-869e-f49e4bc265ee: 'Ferienwohnung Dornumersiel' # Ferienwohnung Dornumersiel
    b338c6ca-cbf6-49e0-8b19-fcfa608a00ba: 'Ferienwohnung Dornumersiel' # Ferienwohnung Dornumersiel
system:
  edition: solo
  live: true
  name: 'Ferienwohnung Dornumersiel'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
