defaultPlacement: end
enableVersioning: true
handle: preise
name: Preise
propagationMethod: all
siteSettings:
  20bbb0e3-e6b3-4759-831d-183394189075: # Ferienwohnung Dornumersiel
    enabledByDefault: true
    hasUrls: true
    template: text-with-sidebar.twig
    uriFormat: preise
type: single
