defaultPlacement: end
enableVersioning: true
handle: startseite
name: Startseite
propagationMethod: all
siteSettings:
  20bbb0e3-e6b3-4759-831d-183394189075: # Ferienwohnung Dornumersiel
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
