defaultPlacement: end
enableVersioning: true
handle: unsereFerienwohnung
name: 'Unsere Ferienwohnung'
propagationMethod: all
siteSettings:
  20bbb0e3-e6b3-4759-831d-183394189075: # Ferienwohnung Dornumersiel
    enabledByDefault: true
    hasUrls: true
    template: holiday-home.twig
    uriFormat: unsere-ferienwohnung
type: single
